### ISSUE TITLE
"Was unable to start python server" under CentOS

### ISSUE THREAD

**Issue by Modius22** [pentaho-labs/pentaho-cpython-plugin#23]
Hi,

we are using the step on CentOS 7 with PDI 8.0 EE. 
During execution we get the following error

`2018/04/25 09:02:14 - text-mining.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) :
2018/04/25 09:02:14 - text-mining.0 - java.io.IOException: Was unable to start python server
2018/04/25 09:02:14 - text-mining.0 - Was unable to start python server
2018/04/25 09:02:14 - text-mining.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : org.pentaho.di.core.exception.KettleException:
2018/04/25 09:02:14 - text-mining.0 - java.io.IOException: Was unable to start python server
2018/04/25 09:02:14 - text-mining.0 - Was unable to start python server
2018/04/25 09:02:14 - text-mining.0 -
2018/04/25 09:02:14 - text-mining.0 - 	at org.pentaho.python.PythonSession.initSession(PythonSession.java:418)
2018/04/25 09:02:14 - text-mining.0 - 	at org.pentaho.di.trans.steps.cpythonscriptexecutor.CPythonScriptExecutorData.initPython(CPythonScriptExecutorData.java:559)
2018/04/25 09:02:14 - text-mining.0 - 	at org.pentaho.di.trans.steps.cpythonscriptexecutor.CPythonScriptExecutor.init(CPythonScriptExecutor.java:112)
2018/04/25 09:02:14 - text-mining.0 - 	at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
2018/04/25 09:02:14 - text-mining.0 - 	at java.lang.Thread.run(Thread.java:748)
2018/04/25 09:02:14 - text-mining.0 - Caused by: java.io.IOException: Was unable to start python server
2018/04/25 09:02:14 - text-mining.0 - 	at org.pentaho.python.PythonSession.launchServer(PythonSession.java:352)
2018/04/25 09:02:14 - text-mining.0 - 	at org.pentaho.python.PythonSession.<init>(PythonSession.java:263)
2018/04/25 09:02:14 - text-mining.0 - 	at org.pentaho.python.PythonSession.initSession(PythonSession.java:416)
2018/04/25 09:02:14 - text-mining.0 - 	... 4 more
2018/04/25 09:02:14 - text-mining.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Error initializing step [text-mining]`

greeting

Christian

**Comment by lopesjef** [comment]
Hi, Modius22!

Did you solve this problem?

**Comment by yusuf-nathani** [comment]
Any solution for this error ?

**Comment by pentaho-aschurman** [comment]
Still is happening
